# Generated by Django 5.1 on 2024-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="profile",
            field=models.ImageField(null=True, upload_to="trainer_profiles/"),
        ),
    ]
