# Generated by Django 5.1 on 2024-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_trainer"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="profile",
            field=models.ImageField(null=True, upload_to="students_profile/"),
        ),
    ]
